version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: asia_dtu
      POSTGRES_USER: asia_dtu
      POSTGRES_PASSWORD: huy778631
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asia_dtu -d asia_dtu"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: vinhhuyqn/asean_dtu:latest  # Use the image from Docker Hub
    volumes:
      - ./config.yaml:/app/config.yaml  # Mount their local config file
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://asia_dtu:huy778631@db/asia_dtu
      - REDIS_URL=redis://redis:6379
    command: python main2.py

volumes:
  postgres_data:
  redis_data: